version: '2'

services: 
#InfluxDB
  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    restart: always
    network_mode: "host"
    ports:
       - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=sensordata
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
volumes:
  influxdb-storage:
    
